TARGET_FILE=/etc/nginx/conf.d/cloudflare.conf
REAL_HEADER=CF-Connecting-IP
echo "# AUTOGENERATED FILE FROM https://gist.github.com/LaurenceJJones/7e7e386bb1f0dae7054c95df2722a4bb" > $TARGET_FILE
for i in `curl -s https://www.cloudflare.com/ips-v4`;
do
   echo "set_real_ip_from $i;" >> $TARGET_FILE
done
for i in `curl -s https://www.cloudflare.com/ips-v6`;
do
   echo "set_real_ip_from $i;" >> $TARGET_FILE
done
echo "real_ip_header $REAL_HEADER;" >> $TARGET_FILE 